WIP: ENH: Bump elastix version to 2023-04-30
InsightSoftwareConsortium/ITKElastix pull request #211
Opened 2023-05-02 15:34 UTC by N-Dekker

Including:

  pull request https://github.com/SuperElastix/elastix/pull/864
  commit https://github.com/SuperElastix/elastix/commit/c3d478e8e3b6b1806862abbd0d777beff9b66346
  "ENH: Upgrade elastix from C++14 to C++17"

  pull request https://github.com/SuperElastix/elastix/pull/856
  commit https://github.com/SuperElastix/elastix/commit/48c64583c8514eac7fa9ad46848be9d100ac80c9
  "ENH: Add SetInitialTransformParameterObject to ElastixRegistrationMethod"

  pull request https://github.com/SuperElastix/elastix/pull/832
  commit https://github.com/SuperElastix/elastix/commit/05d2b40f23d5b1c1438521e505e349bb54fdf7e4
  ENH: Support "ShowProgressPercentage" parameter (`false` by default)

  pull request https://github.com/SuperElastix/elastix/pull/815
  commit https://github.com/SuperElastix/elastix/commit/c4ef707bb9433e687d45a06408393413f2abe64a
  "ENH: Add `ElastixLogLevel` to the ITK interface"

  pull request https://github.com/SuperElastix/elastix/pull/799
  "Replace our xout library with Gabi Melman's spdlog"
  commit https://github.com/SuperElastix/elastix/commit/085a393c858ed9d23a353bf7b54daba1081ee28b
  "ENH: Add spdlog (v1.11.0) to ThirdParty subdirectory as git submodule"

2023-05-05 12:16 UTC, N-Dekker commented
@thewtex Can you please have a look at the CI failures from "Test notebooks / nbmake (ubuntu-22.04)"? 

It says:
> 2023-05-03T15:38:55.7704100Z RuntimeError: module compiled against API version 0x10 but this version of numpy is 0xe . Check the section C-API incompatibility at the Troubleshooting ImportError section at https://numpy.org/devdocs/user/troubleshooting-importerror.html#c-api-incompatibility for indications on how to solve this problem .

2023-05-05 14:06 UTC, thewtex commented
@N-Dekker I rebased https://github.com/InsightSoftwareConsortium/ITKElastix/pull/187 -- it could be related.

2023-05-05 14:22 UTC, N-Dekker commented
Thanks @thewtex, I hope #187 will help.

Actually there are some more build problems with this PR of mine. The main commit, 2189fa84728e8aad2b224ff449e639f3d911e96c has some other failures. I wonder if it's because of the added 3rd party library dependency: elastix now uses the spdlog library, with commit https://github.com/SuperElastix/elastix/commit/085a393c858ed9d23a353bf7b54daba1081ee28b  The dependency is "header only", spdlog is retrieved by git submodule. Do you have a suggestion?

2023-05-05 15:00 UTC, thewtex commented
@N-Dekker is it possible to use [CMake FetchContent](https://cmake.org/cmake/help/latest/module/FetchContent.html) instead of a git submodule? This is easier for developers and library consumers.

Otherwise, maybe `GIT_SUBMODULES` needs to be set here:
https://github.com/InsightSoftwareConsortium/ITKElastix/blob/c36279f04ded427d90d45ac2731e8119647c6c23/CMakeLists.txt#L55-L58

per: https://gitlab.kitware.com/cmake/cmake/-/issues/20579

2023-05-05 19:06 UTC, thewtex commented
@N-Dekker with #187, a rebase on `main` should help with notebook CI :green_apple:

2023-05-05 20:51 UTC, N-Dekker commented
> @N-Dekker is it possible to use [CMake FetchContent](https://cmake.org/cmake/help/latest/module/FetchContent.html) instead of a git submodule? This is easier for developers and library consumers.

Thanks Matt, but I would like to give "git submodule" a fair chance.  One advantage is that GitHub clearly shows which revision of the third party library is being used, for example looking at https://github.com/SuperElastix/elastix/tree/main/ThirdParty

> Otherwise, maybe `GIT_SUBMODULES` needs to be set here:
> 
> https://github.com/InsightSoftwareConsortium/ITKElastix/blob/c36279f04ded427d90d45ac2731e8119647c6c23/CMakeLists.txt#L55-L58
> 
> per: https://gitlab.kitware.com/cmake/cmake/-/issues/20579

Interesting... https://gitlab.kitware.com/cmake/cmake/-/issues/20579 says:

> When FetchContent_Declare is called with a GIT_SUBMODULES argument, it is not honored.  Instead, FetchContent_MakeAvailable() will clone the declared git repository's submodules recursively, even if the named content was declared with GIT_SUBMODULES "".

For elastix, it would be just fine if its submodules are cloned recursively. It actually seems to be the default, when the option `GIT_SUBMODULES` is not specified. As I understand from https://gitlab.kitware.com/cmake/cmake/-/issues/20579#expected-result

However, this CMake issue seems to be specifically about using `FetchContent_MakeAvailable()`.  As far as I can see, [ITKElastix/CMakeLists.txt](https://github.com/InsightSoftwareConsortium/ITKElastix/blob/a7150930fb27f0d2c56bbb466db12431eb180850/CMakeLists.txt) does not use `FetchContent_MakeAvailable`. Did you try `FetchContent_MakeAvailable` before?

The documentation of [FetchContent_Populate](https://cmake.org/cmake/help/latest/module/FetchContent.html#command:fetchcontent_populate) says:

> Note: Where possible, prefer to use [FetchContent_MakeAvailable()](https://cmake.org/cmake/help/latest/module/FetchContent.html#command:fetchcontent_makeavailable) instead of implementing population manually with this command

So would it be OK to you if we replace the existing `FetchContent_Populate(elx)` call from ITKElastix/CMakeLists.txt by the corresponding `FetchContent_MakeAvailable()` call?

2023-05-07 16:23 UTC, thewtex commented
@N-Dekker yes, let's use `FetchContent_MakeAvailable` if it works! :construction_worker_man:

2023-05-08 16:02 UTC, thewtex requested changes
@N-Dekker thanks!!

Minor issue noted inline.

2023-05-08 16:02 UTC, thewtex commented on CMakeLists.txt
> +if(NOT CMAKE_CXX_STANDARD)
`NOT` -> `NOT DEFINED`

2023-05-09 18:33 UTC, thewtex commented on CMakeLists.txt
> +if(NOT CMAKE_CXX_STANDARD)
Yes, I suppose both work with different advantages (explicit vs works with empty string). Let's keep this, then :1234:

2023-05-09 18:34 UTC, thewtex commented
@N-Dekker agreed, the timeout could be longer.

We could add a longer time:

https://github.com/InsightSoftwareConsortium/ITKRemoteModuleBuildTestPackageAction

with the `ctest --timeout` flag.

Perhaps also make it configurable.

@tbirdso

2023-05-09 18:46 UTC, tbirdso commented
> We could add a longer time ... with the ctest --timeout flag.

You can try passing CTest options to the `cxx-build-workflow` in [`build-test-package.yml`](https://github.com/InsightSoftwareConsortium/ITKElastix/blob/main/.github/workflows/build-test-package.yml):

```yml
  with:
    ctest-options: '--timeout'
```

See more details in [ITK reusable workflow documentation](https://github.com/InsightSoftwareConsortium/ITKRemoteModuleBuildTestPackageAction#build-test-cxx-overview).

2023-05-10 20:24 UTC, N-Dekker commented
**All checks have passed**
_4 successful checks_ 
I'm afraid that's not enough, 4 checks only!

2023-05-11 10:24 UTC, N-Dekker commented
FYI, on my PC, the registration of [itkElastixRegistrationMethodTest](https://github.com/InsightSoftwareConsortium/ITKElastix/blob/a7150930fb27f0d2c56bbb466db12431eb180850/test/itkElastixRegistrationMethodTest.cxx) appears _slightly faster_ (~33 seconds) when using the latest revision from the main branch of SuperElastix/elastix, compared to the elastix 5.1.0 release that is used by the main branch of ITKElastix (~34 seconds).

2023-05-11 12:32 UTC, thewtex approved these changes

2023-05-11 14:33 UTC, dzenanz commented
I restarted the builds. At least one of them timed out (6 hours and 6 minutes).

2023-05-11 14:37 UTC, N-Dekker commented
> I restarted the builds. At least one of them timed out (6 hours and 6 minutes).

Thanks @dzenanz So I guess we'd have to wait another 6 hours from now...?

2023-05-11 14:41 UTC, dzenanz commented
Do you have administrative privileges in this repo? If so, you could merge right now.

2023-05-11 14:45 UTC, N-Dekker commented
> Do you have administrative privileges in this repo? If so, you could merge right now.

OK, thanks, but then, what are we missing? It should actually produce python packages for all supported platforms, right? Will they be there?

2023-05-11 14:49 UTC, dzenanz commented
Packages are pushed to PyPI on tagging. I am not sure whether package files are available as artifacts during a PR build like this.

2023-05-11 14:52 UTC, tbirdso commented
> > Do you have administrative privileges in this repo? If so, you could merge right now.
> 
> OK, thanks, but then, what are we missing? It should actually produce python packages for all supported platforms, right? Will they be there?

Echoing @dzenanz , `itk-elastix` packages are not published on PyPI until a release is tagged. So, merging now will not affect PyPI package availability.

Another CI run will typically be triggered on merge into `master` with a merge commit, meaning experimental packages will be available as GitHub Actions artifacts approximately 6 hours from now.

If building for Linux ARM platforms (aarch64) is prohibitive for PR reviews then that platform target could be excluded from the build (see [ITK reusable workflow documentation](https://github.com/InsightSoftwareConsortium/ITKRemoteModuleBuildTestPackageAction#build-test-package-python-overview)), or only built when CI runs on the `master` branch. In the future we aim to speed up the build process with better cross-compilation for ARM and/or with unified Python packages.

2023-05-11 14:57 UTC, N-Dekker commented
Thanks @tbirdso 

> Another CI run will typically be triggered on merge into master with a merge commit, meaning experimental packages will be available as GitHub Actions artifacts approximately 6 hours from now.

Are there no artifacts (Python wheels) available from a successful PR _before_ the merge?

2023-05-11 15:31 UTC, N-Dekker commented
> In the future we aim to speed up the build process with better cross-compilation for ARM and/or with unified Python packages.

I see it tries to build 11 wheels with each PR, while it is not even being merged. Wouldn't 1 wheel per platform (linux, macos, windows), with one Python version, be OK already?

Also I wonder, does the CI build both ITK and elastix from scratch with each PR trigger? Maybe those binaries could be cached somehow, if either of the two libraries are unmodified?

Unfortunately I'm not a yml/CI expert. So I'm just asking.

2023-05-11 15:34 UTC, dzenanz commented
If I remember correctly, ITK build is cached, but elastix gets rebuilt each time. That allows us the flexibility of just changing the SHA of elastix.

2023-05-11 15:50 UTC, N-Dekker commented
@dzenanz @tbirdso @thewtex By the way, I'm curious, did any of you actually change the timeout threshold for CDash/CTest already? Because just today those timeout failures from itkElastixRegistrationMethodTest disappeared and the "Acceptable Range" appeared to have become more "acceptable", as I mentioned at https://github.com/InsightSoftwareConsortium/ITKElastix/pull/211#issuecomment-1543902215  (Even though I did not yet process Matt's PR https://github.com/N-Dekker/ITKElastix/pull/1).

2023-05-11 15:56 UTC, dzenanz commented
> change the timeout threshold

Not me.

2023-05-16 10:04 UTC, N-Dekker commented
The CI still fails, including cancellations of [build-linux-py (311, 2014-x64)](https://github.com/InsightSoftwareConsortium/ITKElastix/actions/runs/4945300030/jobs/8928563770?pr=211) and [build-linux-py (311, 2014-x64)](https://github.com/InsightSoftwareConsortium/ITKElastix/actions/runs/4945300030/jobs/8928563848?pr=211)

But I'm hopeful that a `rebase main` might help, due to PR #214 , and I also have another C++ PERF improvement from elastix to be included. Please wait, I'll do a force-push.

2023-05-16 14:14 UTC, N-Dekker commented
🎉 Approved by the CI 🥇

2023-05-16 15:21 UTC, merged

2023-05-16 15:25 UTC, NHPatterson commented
Hi all, I'm not really a part of this conversation but I did notice that the new feature did not include any specific tests to ensure images with images with dtypes besides float32 and double work. I took the liberty of downloading the artifacts from the most recent CI and tried them out. Good news a lot more dtypes are supported for registration!

For reference:
```python

import itk
import numpy as np

parameter_object = itk.ParameterObject.New()
default_rigid_parameter_map = parameter_object.GetDefaultParameterMap('rigid')
parameter_object.AddParameterMap(default_rigid_parameter_map)

int_dtypes = (np.uint8, np.int16, np.uint16)
for dtype in int_dtypes:
    image = np.random.randint(0, 100, (1024,1024), dtype=dtype)
    itk_image = itk.GetImageFromArray(image)
    
    result_image, result_transform_parameters = itk.elastix_registration_method(
    itk_image, itk_image,
    parameter_object=parameter_object,
    log_to_console=False)
    
    assert itk.template(result_image)[1][0] == itk.template(itk_image)[1][0]

    
floating_dtypes = (np.float32, np.double)
for dtype in floating_dtypes:
    image = np.random.rand(1024*1024).astype(dtype).reshape(1024,1024)
    itk_image = itk.GetImageFromArray(image)
    
    result_image, result_transform_parameters = itk.elastix_registration_method(
    itk_image, itk_image,
    parameter_object=parameter_object,
    log_to_console=False)
    
    assert itk.template(result_image)[1][0] == itk.template(itk_image)[1][0]
```

Thanks for this.

2023-05-16 15:50 UTC, N-Dekker commented
@NHPatterson You're welcome, I'm very glad to hear so! I did test the extended pixel type support quite extensively at the C++ side (as part of the GoogleTest unit tests at [SuperElastix/elastix/Core/Main/GTesting](https://github.com/SuperElastix/elastix/tree/b9b8e20aef83f94ed38a81cc38625a1bfddf1053/Core/Main/GTesting)), but I only did a few local checks on a drafty Jupyter notebook (also using a wheel from the CI ) to see if it works. So thanks for checking it as well!